name = "KomePackage"
uuid = "48ee232c-abb0-4c44-8ffa-3b888a936b6a"
authors = ["fkazuki51 <8116067@ed.tus.ac.jp>"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
